In [1]:
import pandas as pd

price_df = pd.read_csv('../data/ag_data/canola_prices_monthly.csv')
price_df

       month       close        open   high    low    volume
0    2010-08  455.441667  455.575000  469.4  435.7  139120.0
1    2010-09  469.661905  468.809524  487.3  453.0  239010.0
2    2010-10  500.505000  497.870000  535.7  461.0  188380.0
3    2010-11  538.690476  538.633333  563.8  519.0  114640.0
4    2010-12  565.495238  564.071429  585.4  536.9  181810.0
..       ...         ...         ...    ...    ...       ...
168  2024-08  588.195238  587.885714  624.0  561.4  546880.0
169  2024-09  581.815789  580.852632  619.1  538.8  549550.0
170  2024-10  621.431818  618.786364  644.6  594.8  376000.0
171  2024-11  615.575000  618.455000  652.7  563.6  328750.0
172  2024-12  605.340000  603.260000  626.5  570.0  385420.0

[173 rows x 6 columns]

In [2]:
prod_df = pd.read_csv('../data/ag_data/top_producers.csv')
prod_df

,country,year,production_tonnes,pesticides_tonnes,nitrogen_kilo_per_acre
0,Australia,2000,2426000.0,33475.48,36.01
1,Canada,2000,7205300.0,39718.43,34.22
2,China,2000,11380579.0,241520.90,170.25
3,France,2000,3476819.0,97878.00,106.93
4,Germany,2000,3585661.0,35273.17,122.96
...,...,...,...,...,...
179,France,2022,4516540.0,NaN,NaN
180,Germany,2022,4294900.0,NaN,NaN
181,India,2022,11963090.0,NaN,NaN
182,Poland,2022,3487070.0,NaN,NaN
183,World,2022,87221224.0,NaN,NaN

In [3]:
weather_df = pd.read_csv('../data/weather_data/weather_data.csv')
weather_df[['year','month']] = weather_df['month'].str.split('-',expand=True)
weather_df = weather_df.groupby(['year','location_ref']).agg(list)
weather_df = weather_df.reset_index()
weather_df = weather_df[weather_df['year'] != '2025']
monthly_cols = list(weather_df.columns)
for col in ['year', 'location_ref', 'month']:
    monthly_cols.remove(col)
for col in monthly_cols:
    # Expand the list into new columns
    new_cols = weather_df[col].apply(pd.Series)
    
    # Rename the new columns (optional)
    new_cols.columns = [col + '_01', col + '_02', col + '_03', col + '_04',
                        col + '_05', col + '_06', col + '_07', col + '_08',
                        col + '_09', col + '_10', col + '_11', col + '_12']
    
    weather_df = pd.concat([weather_df, new_cols], axis=1)
monthly_cols.append('month')
weather_df.drop(monthly_cols, axis=1, inplace=True)
weather_df['year'] = weather_df['year'].astype(int)
weather_df

,year,location_ref,temp_01,temp_02,temp_03,temp_04,temp_05,temp_06,temp_07,temp_08,...,max_gust_03,max_gust_04,max_gust_05,max_gust_06,max_gust_07,max_gust_08,max_gust_09,max_gust_10,max_gust_11,max_gust_12
0,2020,1,-15.551492,-12.447758,-4.958011,4.261389,9.592191,14.993124,19.143265,14.797903,...,95.399994,74.880000,86.760000,56.880000,68.400000,54.000000,68.760000,75.600000,60.839996,63.000000
1,2020,2,-16.664406,-14.233925,-9.495992,0.853139,4.632435,10.465917,13.575582,11.092650,...,106.200000,86.039990,109.079994,84.600000,107.279990,92.520000,80.640000,96.840000,90.000000,78.479996
2,2020,3,4.620390,7.171235,11.722809,13.747013,20.099690,22.166319,22.922000,23.434166,...,43.560000,34.200000,40.320000,37.440000,33.480000,42.120000,29.880000,29.160000,34.920000,30.239998
3,2020,4,2.591637,6.659054,9.199836,12.355055,18.650710,21.330402,22.679405,22.511192,...,91.799995,68.400000,84.960000,82.439995,91.439995,67.320000,47.519997,50.760000,66.600000,56.160000
4,2020,5,1.951901,5.070296,5.046726,11.023431,12.127372,15.991278,18.901161,19.320112,...,81.720000,62.639996,64.439995,60.120003,65.520004,71.640000,60.479996,61.560000,52.920000,56.519997
5,2020,6,3.258637,5.434101,5.007562,10.308444,12.178663,17.916498,18.607023,21.157629,...,89.279990,60.120003,63.720000,66.960000,69.120000,86.039990,46.079998,61.920002,64.799995,66.240000
6,2020,7,3.029460,4.096497,4.189540,8.688250,11.323882,18.026861,18.028452,20.137995,...,81.720000,62.279995,61.920002,56.880000,54.719997,61.920002,55.800000,80.280000,57.239998,51.120000
7,2020,8,12.440495,16.551800,20.738008,28.129570,31.965694,32.743180,31.296879,29.173223,...,50.039997,54.719997,66.240000,61.199997,48.239998,63.000000,40.680000,35.640000,40.680000,36.719997
8,2020,9,4.485301,6.354420,10.345113,13.816138,21.118902,24.710790,24.519442,28.225557,...,50.399998,51.839996,50.399998,61.199997,63.720000,47.160000,44.280000,45.360000,54.719997,63.360000
9,2020,10,12.899261,12.179669,14.406048,15.139236,18.435080,22.317291,24.859072,27.030376,...,108.360000,118.799995,81.000000,109.799995,85.320000,52.920000,124.200000,101.520000,92.880000,118.079994
10,2021,1,-21.572393,-16.879583,-6.241075,1.206389,6.071156,15.613264,17.990780,15.808588,...,73.799995,78.479996,77.400000,76.320000,51.120000,58.679996,68.400000,59.039997,66.960000,71.280000
11,2021,2,-22.223210,-16.345884,-8.234702,-4.182000,0.949774,9.180639,13.365702,11.005621,...,135.359990,100.799995,106.200000,95.039990,81.720000,93.600000,72.360000,86.399994,90.360000,71.280000
12,2021,3,2.525632,9.650460,11.958696,14.247777,19.012592,21.491596,23.483025,22.749958,...,41.039997,36.719997,41.399998,51.839996,35.640000,33.839996,37.800000,32.760002,47.519997,34.200000
13,2021,4,2.617309,8.044515,9.344661,11.967694,17.347887,20.870958,22.863478,21.988410,...,69.479996,62.639996,97.920000,64.439995,81.000000,65.880000,56.160000,78.840000,61.199997,51.120000
14,2021,5,-0.241446,2.869616,4.162317,6.401972,10.391014,18.670307,18.081270,16.623405,...,78.120000,69.120000,74.880000,69.479996,50.039997,62.279995,46.800000,83.880000,77.039990,67.320000
15,2021,6,0.574632,0.020815,4.528327,5.882056,11.276580,19.462055,18.970398,16.837332,...,94.679990,63.000000,88.920000,55.800000,61.199997,65.520004,57.600000,92.520000,56.519997,63.720000
16,2021,7,-1.666239,-3.033134,3.237457,5.820334,11.710508,19.654570,20.642160,17.085709,...,69.840000,68.039990,67.320000,58.320000,57.239998,62.279995,76.679990,88.560000,73.799995,81.360000
17,2021,8,13.017376,18.495184,25.056623,28.876791,30.107027,32.509640,31.135118,29.645199,...,69.120000,71.280000,51.480000,56.880000,50.039997,49.680000,54.360000,42.480000,33.480000,34.920000
18,2021,9,2.632277,7.438291,9.721591,14.235792,20.286710,25.663637,27.152440,26.219710,...,46.800000,76.679990,48.600000,57.600000,84.960000,48.600000,58.679996,57.239998,59.760000,51.839996
19,2021,10,12.252486,11.791295,13.683737,14.508680,19.308735,21.248404,25.031588,26.222042,...,108.720000,104.039990,90.360000,106.560000,89.640000,95.399994,73.079994,148.319990,90.000000,118.799995
20,2022,1,-19.309624,-16.805326,-7.749677,1.432292,9.799785,16.609653,18.095148,13.652003,...,75.960000,73.079994,68.760000,56.519997,53.639996,58.320000,60.479996,64.799995,53.280000,87.120000
21,2022,2,-17.445858,-17.524456,-11.868572,-3.287209,6.039223,11.278903,11.737207,9.345406,...,87.479996,83.159996,88.920000,81.000000,66.960000,64.079994,81.720000,92.880000,76.679990,87.840000
22,2022,3,4.839207,3.773676,14.190684,15.369721,17.644112,22.006527,25.217903,26.207754,...,39.960000,55.800000,33.120000,46.079998,42.839996,34.920000,29.160000,30.239998,40.320000,31.319998
23,2022,4,1.965696,-0.369176,10.528935,13.349568,15.373895,20.253805,23.734312,24.069527,...,88.560000,77.760000,63.360000,67.320000,67.320000,63.360000,47.880000,68.760000,77.039990,64.079994
24,2022,5,1.213191,3.804661,4.582478,7.486208,14.905462,18.894890,20.014938,19.799078,...,48.960000,88.560000,51.480000,50.760000,46.440000,51.120000,58.320000,56.880000,54.360000,62.279995
25,2022,6,3.239148,4.399461,3.858436,7.718236,14.960181,19.282331,19.990423,21.197817,...,54.719997,94.679990,63.720000,52.560000,54.719997,47.160000,54.719997,55.079998,57.960000,64.079994
26,2022,7,1.144379,3.148786,2.837793,6.911583,13.597605,18.633112,18.915012,21.292631,...,51.120000,74.520004,81.000000,55.440000,58.320000,47.880000,54.360000,57.239998,41.039997,53.280000
27,2022,8,11.820131,16.222490,25.639217,32.609360,34.281890,33.726097,29.587671,28.480951,...,46.440000,59.039997,54.719997,63.360000,47.880000,59.760000,44.639996,38.160000,36.000000,33.120000
28,2022,9,3.160502,3.121476,10.631403,15.759958,20.964401,27.106764,28.645382,29.039536,...,62.279995,52.920000,51.839996,60.839996,52.199997,52.199997,75.960000,51.839996,55.800000,51.480000
29,2022,10,9.898319,9.700297,13.476814,15.977709,18.474060,21.019167,25.213173,27.452417,...,110.520000,106.560000,89.279990,113.760000,86.760000,67.320000,69.840000,113.039990,109.799995,104.399994
30,2023,1,-19.387850,-12.868720,-4.094704,-1.105694,7.835470,14.664097,18.170687,15.982379,...,78.120000,82.079994,70.920000,72.000000,57.239998,71.640000,67.679990,72.360000,59.039997,75.240000
31,2023,2,-21.619446,-15.383161,-8.817162,-7.160403,1.033309,10.937861,13.518726,12.631562,...,105.120000,97.560000,91.439995,85.679990,76.320000,61.560000,64.799995,100.439995,77.760000,79.560000
32,2023,3,3.435107,7.678735,11.763064,16.498749,19.310913,21.143680,24.003386,22.955671,...,48.600000,45.000000,44.280000,34.200000,58.320000,31.319998,46.440000,30.599998,38.160000,41.039997
33,2023,4,3.019796,4.283875,9.754137,13.516999,17.583437,20.609568,23.006420,21.730818,...,57.239998,77.039990,69.479996,59.760000,64.799995,46.079998,47.880000,46.440000,61.560000,64.799995
34,2023,5,2.622263,2.355851,6.234159,7.178778,13.298809,18.960236,19.870247,19.263863,...,80.280000,72.360000,45.000000,54.719997,56.160000,72.360000,44.639996,62.279995,71.280000,83.880000
35,2023,6,3.918045,3.140905,5.577387,7.474764,13.322884,19.224277,19.739819,18.964079,...,80.640000,64.799995,47.880000,55.440000,64.079994,70.560000,52.920000,64.439995,67.679990,69.840000
36,2023,7,2.792094,0.898934,3.823815,7.469778,12.930133,18.587557,19.474620,19.392834,...,63.360000,55.800000,50.039997,55.800000,60.479996,64.439995,50.039997,65.880000,72.000000,77.400000
37,2023,8,11.727860,18.849127,21.734715,26.630056,29.437605,30.622972,29.771610,30.684109,...,40.320000,55.800000,57.600000,57.600000,45.000000,41.760002,51.480000,46.800000,42.839996,32.039997
38,2023,9,2.979723,4.354958,11.008285,15.591555,20.484562,24.317389,27.655396,26.808620,...,55.440000,56.519997,55.079998,54.719997,55.440000,44.639996,45.000000,41.760002,54.000000,54.719997
39,2023,10,11.416330,11.122099,14.312366,15.886181,17.890524,21.517500,25.302082,27.551546,...,96.840000,87.479996,110.880000,101.880000,78.479996,119.159990,65.159996,99.000000,108.360000,105.840000
40,2024,1,-17.666882,-16.733606,-5.578441,2.019306,10.345685,16.603819,21.608590,17.965443,...,66.960000,79.200000,78.840000,56.880000,46.079998,49.680000,76.679990,73.079994,56.880000,56.880000
41,2024,2,-18.555063,-19.342617,-9.568439,-2.275056,6.629210,11.172028,15.730958,13.723431,...,101.880000,93.240000,88.560000,86.039990,64.439995,75.240000,60.839996,96.120000,94.679990,78.840000
42,2024,3,6.087325,5.554066,12.339341,17.208124,19.472136,21.380278,24.199759,25.580940,...,46.079998,46.800000,37.440000,34.920000,29.880000,33.120000,42.120000,28.800000,48.239998,29.519999
43,2024,4,3.421812,2.723279,9.569998,14.990402,17.133774,19.429083,23.702590,23.029001,...,71.640000,81.720000,55.440000,63.720000,74.520004,48.600000,57.600000,55.079998,51.480000,43.199997
44,2024,5,0.768567,6.543500,7.866685,9.931209,14.068432,17.610930,19.557880,20.333015,...,59.399998,83.159996,52.560000,58.679996,50.760000,47.880000,63.360000,55.800000,73.079994,70.920000
45,2024,6,0.978194,6.563770,6.782159,10.275180,15.312467,17.220804,19.851310,21.187265,...,66.960000,65.159996,60.839996,57.960000,60.479996,54.719997,61.560000,74.880000,74.880000,64.079994
46,2024,7,-0.072691,5.157057,6.369917,10.148806,16.283962,18.115194,19.801905,20.119246,...,50.039997,60.479996,54.719997,57.600000,66.960000,50.039997,61.920002,61.560000,62.279995,70.920000
47,2024,8,11.179876,16.223852,22.115025,29.509151,35.265495,35.207558,30.694324,27.813880,...,50.399998,55.800000,65.159996,55.440000,46.800000,54.360000,56.160000,39.960000,31.319998,37.800000
48,2024,9,2.459293,3.589908,9.188795,15.252528,20.346188,25.791348,28.851160,29.066082,...,48.600000,48.600000,68.039990,56.880000,67.679990,39.239998,67.679990,54.000000,52.560000,43.560000
49,2024,10,12.608736,12.139367,12.562970,16.383265,19.623320,21.992987,26.210417,27.051477,...,174.240000,141.840000,89.279990,115.559990,87.840000,107.279990,82.079994,95.039990,92.159996,97.200000

In [4]:
location_df  = pd.read_csv('../data/weather_data/weather_locations.csv')
location_df

,region,country,weight,latitude,longitude,location_ref,lat_num,lon_num,plant_mon,harvest_mon
0,Alberta,Canada,0.25,"51°40'36.2""N","113°12'03.1""W",1,51.40,113.12,5,9
1,Saskatchewan,Canada,0.75,"51°20'05.3""N","104°27'20.7""W",2,51.20,104.27,5,9
2,West,China,0.50,"28°08'09.8""N","104°32'53.4""E",3,28.09,104.33,9,5
3,East,China,0.50,"27°54'11.9""N","114°24'50.0""E",4,27.54,114.25,9,5
4,France,France,1.00,"48°28'25.5""N","11°20'13.6""E",5,48.28,11.20,9,7
5,Germany,Germany,1.00,"51°44'31.0""N","11°43'54.0""E",6,51.44,11.44,9,7
6,Poland,Poland,1.00,"53°26'11.3""N","18°09'57.5""E",7,53.26,18.10,9,7
7,India,India,1.00,"28°14'16.4""N","76°33'14.4""E",8,28.14,76.33,11,4
8,West,Australia,0.50,"33°19'41.5""S","120°01'13.1""E",9,33.19,120.01,6,10
9,East,Australia,0.50,"35°27'11.1""S","146°52'47.3""E",10,35.27,146.52,6,10

In [5]:
full_df = prod_df.merge(location_df, how='outer', on='country')
full_df

,country,year,production_tonnes,pesticides_tonnes,nitrogen_kilo_per_acre,region,weight,latitude,longitude,location_ref,lat_num,lon_num,plant_mon,harvest_mon
0,Australia,2000,2426000.0,33475.48,36.01,West,0.5,"33°19'41.5""S","120°01'13.1""E",9.0,33.19,120.01,6.0,10.0
1,Australia,2000,2426000.0,33475.48,36.01,East,0.5,"35°27'11.1""S","146°52'47.3""E",10.0,35.27,146.52,6.0,10.0
2,Australia,2001,1775019.0,32709.51,37.95,West,0.5,"33°19'41.5""S","120°01'13.1""E",9.0,33.19,120.01,6.0,10.0
3,Australia,2001,1775019.0,32709.51,37.95,East,0.5,"35°27'11.1""S","146°52'47.3""E",10.0,35.27,146.52,6.0,10.0
4,Australia,2002,1755863.0,26650.16,36.37,West,0.5,"33°19'41.5""S","120°01'13.1""E",9.0,33.19,120.01,6.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,World,2018,75564170.0,3292014.00,66.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
249,World,2019,71827810.0,3382370.20,63.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,World,2020,72389630.0,3398783.50,66.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,World,2021,71958180.0,3531959.00,65.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,World,2022,87221224.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
full_df = full_df[full_df['country'] != 'World']
full_df.drop(['latitude','longitude','lat_num','lon_num'], axis=1, inplace=True)
full_df

/tmp/ipykernel_31812/3400049926.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_df.drop(['latitude','longitude','lat_num','lon_num'], axis=1, inplace=True)

,country,year,production_tonnes,pesticides_tonnes,nitrogen_kilo_per_acre,region,weight,location_ref,plant_mon,harvest_mon
0,Australia,2000,2426000.0,33475.48,36.01,West,0.5,9.0,6.0,10.0
1,Australia,2000,2426000.0,33475.48,36.01,East,0.5,10.0,6.0,10.0
2,Australia,2001,1775019.0,32709.51,37.95,West,0.5,9.0,6.0,10.0
3,Australia,2001,1775019.0,32709.51,37.95,East,0.5,10.0,6.0,10.0
4,Australia,2002,1755863.0,26650.16,36.37,West,0.5,9.0,6.0,10.0
...,...,...,...,...,...,...,...,...,...,...
225,Poland,2018,2105610.0,23178.00,69.99,Poland,1.0,7.0,9.0,7.0
226,Poland,2019,2268850.0,24281.00,72.56,Poland,1.0,7.0,9.0,7.0
227,Poland,2020,2982880.0,24168.00,63.28,Poland,1.0,7.0,9.0,7.0
228,Poland,2021,3050910.0,26534.00,63.67,Poland,1.0,7.0,9.0,7.0
229,Poland,2022,3487070.0,NaN,NaN,Poland,1.0,7.0,9.0,7.0

In [7]:
final_df = full_df.merge(weather_df, how='outer', on=['year', 'location_ref'])
final_df

,country,year,production_tonnes,pesticides_tonnes,nitrogen_kilo_per_acre,region,weight,location_ref,plant_mon,harvest_mon,...,max_gust_03,max_gust_04,max_gust_05,max_gust_06,max_gust_07,max_gust_08,max_gust_09,max_gust_10,max_gust_11,max_gust_12
0,Canada,2000,7205300.0,39718.43,34.22,Alberta,0.25,1.0,5.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Canada,2000,7205300.0,39718.43,34.22,Saskatchewan,0.75,2.0,5.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,China,2000,11380579.0,241520.90,170.25,West,0.50,3.0,9.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,China,2000,11380579.0,241520.90,170.25,East,0.50,4.0,9.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,France,2000,3476819.0,97878.00,106.93,France,1.00,5.0,9.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,NaN,2024,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,...,66.960000,65.159996,60.839996,57.96000,60.479996,54.719997,61.560000,74.88000,74.880000,64.079994
246,NaN,2024,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,...,50.039997,60.479996,54.719997,57.60000,66.960000,50.039997,61.920002,61.56000,62.279995,70.920000
247,NaN,2024,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,...,50.399998,55.800000,65.159996,55.44000,46.800000,54.360000,56.160000,39.96000,31.319998,37.800000
248,NaN,2024,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,...,48.600000,48.600000,68.039990,56.88000,67.679990,39.239998,67.679990,54.00000,52.560000,43.560000
249,NaN,2024,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,...,174.240000,141.840000,89.279990,115.55999,87.840000,107.279990,82.079994,95.03999,92.159996,97.200000